// Local preview server for the static site — matches exactly what GitHub
// Pages serves in production: files from public/, nothing else. There's no
// live API here on purpose; data comes from public/data/opportunities.json,
// regenerated by `pnpm run sync` (see .github/workflows/refresh-and-deploy.yml
// for the scheduled version of that).
import { createServer } from "node:http";
import { existsSync, readFileSync } from "node:fs";
import { extname, join } from "node:path";

const port = Number(process.env.PORT ?? 8090);
const publicDir = join(process.cwd(), "public");
const types: Record<string, string> = {
  ".html": "text/html", ".css": "text/css", ".js": "text/javascript",
  ".json": "application/json", ".svg": "image/svg+xml", ".png": "image/png",
  ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".webp": "image/webp",
};

createServer((request, response) => {
  if (request.method === "GET" && request.url === "/health") {
    response.writeHead(200, { "content-type": "application/json" });
    response.end(JSON.stringify({ status: "ok", service: "openshelf-static" }));
    return;
  }
  const route = request.url === "/" ? "/index.html" : (request.url ?? "/index.html");
  const safe = route.split("?")[0].replace(/\.\./g, "");
  const target = join(publicDir, safe);
  if (!existsSync(target)) {
    response.writeHead(404);
    response.end("Not found");
    return;
  }
  const data = readFileSync(target);
  response.writeHead(200, { "content-type": `${types[extname(safe)] ?? "application/octet-stream"}; charset=utf-8` });
  response.end(data);
}).listen(port, "0.0.0.0", () => console.log(`OpenShelf static preview at http://localhost:${port}`));
